import type { NextPage } from "next";
import Head from "next/head";
import { Typography } from "@mui/material";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography component="h1" variant="h1">
        INDEX
      </Typography>
    </>
  );
};

export default Home;
